import * as React from 'react'
import {useState, useContext, createContext} from 'react'

const LanguageContext = createContext({});

export function LanguageProvider({children}) {

  const languages = {
    'english' : {
        login: 'Login',
        register: 'Register',
        email: 'E-mail',
        firstName: 'First name',
        lastName: 'Last name',
        id: 'Social security number',
        birthdate: 'Birthdate',
        password: 'Password',
        account: 'Account',
        balance: 'Current balance:',
        transference: 'Transfer',
        deposit: 'Deposit',
        transactions: 'Transactions',
        donate: 'Donate',
        myProfile: 'My Profile',
        help: 'Help',
        contactUs: 'Contact us!',
        name: 'Name',
        subject: 'Subject',
        message: 'Message',
        send: 'Send',
        cancel: 'Cancel',
        settings: 'Settings',
        selectLanguage: 'Select language',
        value: 'Value (R$)',
        destination: 'Destination',
        transfer: 'Transfer',
        pix: 'Pix',
        boleto: 'Pay slip',
        credit: 'Credit',
        animals: 'Animals',
        education: 'Education',
        kids: 'Kids',
        donation: 'Donation',
        chooseProfilePhoto: 'Choose your profile picture',
        loginFailedToast: 'Incorrect username or password',
        loginFailedToast2: 'Please check your details and try again',
        registerFailedToast: 'An error has occurred',
        registerFailedToast2: 'Please check your data and try again.',
        registerSuccessToast: 'User created successfully!',
        registerSuccessToast2: 'Enter your details and login to the app',
        transferSuccessToast: 'Transaction completed successfully!',
        transferSuccessToast2: 'Your transfer is complete',
        depositFailedToast: 'Unable to complete transaction',
        depositFailedToast2: 'Check the entered data and try again',
        depositSuccessToast: 'Transaction completed successfully!',
        depositSuccessToast2: 'Thanks for the preference.',
        donateSuccessToast: 'Donation completed successfully!',
        donateSuccessToast2: 'Thanks for your help!',
        donateFailedNetworkToast: 'There was an error with our database!',
        donateFailedNetworkToast2: 'Try again later',
        donateFailedToast: 'Unable to perform transaction',
        donateFailedToast2: 'Check entered data and try again',
        helpSuccessToast: 'Email sent successfully.',
        helpSuccessToast2: 'Thanks for giving us this feedback!',
        helpFailedToast: 'Invalid field',
        helpFailedToast2: 'Please check the entered data and try again',
        outOfMoneyToast1: 'Insufficient balance',
        outOfMoneyToast2: 'Unable to perform operation',
        cannotSendToYourselfToast1: 'Cannot transfer to self',
        cannotSendToYourselfToast2: 'Try again.'
    },
      'portuguese': {
  
        login: 'Entrar',
        register: 'Registrar',
        email: 'E-mail',
        firstName: 'Primeiro nome',
        lastName: 'Sobrenome',
        id: 'CPF',
        birthdate: 'Data de nascimento',
        password: 'Senha',
        account: 'Conta',
        balance: 'Saldo atual',
        transference: 'Transferência',
        deposit: 'Depositar',
        transactions: 'Transações',
        donate: 'Doar',
        profile: 'Meu perfil',
        help: 'Ajuda',
        contactUs: 'Entre em contato conosco!',
        name: 'Nome',
        subject: 'Assunto',
        message: 'Mensagem',
        send: 'Enviar',
        cancel: 'Cancelar',
        settings: 'Configuração',
        selectLanguage: 'Selecionar idioma',
        value: 'Valor (R$)',
        destination: 'CPF do Destinatário',
        transfer: 'Transferir',
        pix: 'Pix',
        boleto: 'Boleto',
        credit: 'Crédito',
        animals: 'Animais',
        education: 'Educação',
        kids: 'Crianças',
        myProfile: 'Meu perfil',
        donation: 'Doação',
        chooseProfilePhoto: 'Escolha seu avatar',
        loginFailedToast: 'Usuário ou senha incorretos',
        loginFailedToast2: 'Verifique seus dados e tente novamente',
        registerFailedToast: 'Ocorreu um erro',
        registerFailedToast2: 'Verifique seus dados e tente novamente.',
        registerSuccessToast:  'Usuário criado com sucesso!',
        registerSuccessToast2:  'Insira seus dados e faça login no app',
        transferSuccessToast: 'Transação concluída com sucesso!',
        transferSuccessToast2: 'Sua transferência foi concluída',
        depositFailedToast: 'Não foi possível efetuar a transação',
        depositFailedToast2: 'Confira os dados inseridos e tente novamente',
        depositSuccessToast: 'Transação concluída com sucesso!',
        depositSuccessToast2: 'Obrigado pela preferência.',
        donateSuccessToast: 'Doação concluída com sucesso!',
        donateSuccessToast2: 'Obrigado pela sua ajuda!',
        donateFailedNetworkToast: 'Ocorreu um erro com nosso banco de dados!',
        donateFailedNetworkToast2: 'Tente novamente mais tarde',
        donateFailedToast: 'Não foi possível efetuar a transação',
        donateFailedToast2: 'Confira os dados inseridos e tente novamente',
        helpSuccessToast: 'Email enviado com sucesso.',
        helpSuccessToast2: 'Obrigado por nos deixar esse feedback!',
        helpFailedToast: 'Campo inválido',
        helpFailedToast2: 'Verifique os dados inseridos e tente novamente',
        outOfMoneyToast1: 'Saldo insuficiente',
        outOfMoneyToast2: 'Não foi possível realizar a operação',
        cannotSendToYourselfToast1: 'Não é possível transferir para si mesmo',
        cannotSendToYourselfToast2: 'Tente novamente.'


      },
      'spanish': {
        login: 'Acceso',
        register: 'Registro',
        email: 'E-mail',
        firstName: 'Primer nombre',
        lastName: 'Apellido',
        id: 'Número de identidad',
        birthdate: 'Fecha de nacimiento',
        password: 'Clave',
        account: 'Cuenta',
        balance:  'Saldo actual:',
        transference: 'Transferir',
        deposit: 'Depósito',
        transactions: 'Facturas',
        donate:  'Donar',
        myProfile:  'Mi perfil',
        help:  'Ayudar',
        contactUs: '¡Contáctenos!',
        name:  'Nombre',
        subject: 'Asunto',
        message: 'Mensaje',
        send: 'Enviar',
        cancel: 'Cancelar',
        settings: 'Ajustes',
        selectLanguage: 'Seleccione el idioma',
        value:  'Valor (R$)',
        destination: 'Destino',
        transfer: 'Transferir',
        pix: 'Pix',
        boleto: 'Billete',
        credit: 'Crédito',
        animals: 'Animales',
        education: 'Educación',
        kids: 'Niños',
        donation: 'Doación',
        chooseProfilePhoto: 'Elige tu foto de perfil',
        loginFailedToast: 'Usuario o contraseña incorrectos',
        loginFailedToast2: 'Por favor, compruebe sus datos y vuelva a intentarlo',
        registerFailedToast: 'Ha ocurrido un error',
        registerFailedToast2: 'Por favor revisa tus datos y vuelve a intentarlo.',
        registerSuccessToast: '¡Usuario creado con éxito!',
        registerSuccessToast2: 'Ingrese sus datos e inicie sesión en la aplicación',
        transferSuccessToast: '¡Transacción completada con éxito!',
        transferSuccessToast2: 'Tu transferencia está completa',
        depositFailedToast: 'No se pudo completar la transacción',
        depositFailedToast2: 'Verifique los datos ingresados ​​y vuelva a intentarlo',
        depositSuccessToast: '¡Transacción completada con éxito!',
        depositSuccessToast2: 'Gracias por la preferencia.',
        donateSuccessToast: '¡La donación se completó con éxito!',
        donateSuccessToast2: '¡Gracias por tu ayuda!',
        donateFailedNetworkToast: '¡Hubo un error con nuestra base de datos!',
        donateFailedNetworkToast2: 'Vuelve a intentarlo más tarde',
        donateFailedToast: 'No se pudo realizar la transacción',
        donateFailedToast2: 'Verifique los datos ingresados ​​y vuelva a intentarlo',
        helpSuccessToast: 'Correo electrónico enviado con éxito.',
        helpSuccessToast2: '¡Gracias por darnos este comentario!',
        helpFailedToast: 'Campo no válido',
        helpFailedToast2: 'Por favor, compruebe los datos introducidos y vuelva a intentarlo',
        outOfMoneyToast1: 'Saldo insuficiente',
        outOfMoneyToast2: 'No se puede realizar la operación',
        cantSendToYourselfToast1: 'No se puede enviar a sí mismo',
        cantSendToYourselfToast2: 'Inténtalo de nuevo.'
      }
  }

  const [lang, setLang] = useState('portuguese')

  function changeLanguage(language) {
    setLang(language)
  }

  return (
    <LanguageContext.Provider value={{lang, changeLanguage, languages}}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(){
  const context = useContext(LanguageContext);
  const {lang, changeLanguage, languages} = context;
  return { lang, changeLanguage, languages };
}